// Package config defines the casambi-go configuration file and its on-disk
// location. Everything user-specific — network IDs, Hue bridge credentials,
// which lights participate in reactive mode — lives here instead of in code.
//
// The config lives in $XDG_CONFIG_HOME/casambi-go/config.yaml (defaulting to
// ~/.config/casambi-go/config.yaml), next to the cached Casambi credentials
// and the BPM cache. `casambi-go setup` writes it interactively.
package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

type Config struct {
	Server   ServerConfig   `yaml:"server" json:"server"`
	Casambi  CasambiConfig  `yaml:"casambi" json:"casambi"`
	Hue      HueConfig      `yaml:"hue" json:"hue"`
	Spotify  SpotifyConfig  `yaml:"spotify" json:"spotify"`
	Reactive ReactiveConfig `yaml:"reactive" json:"reactive"`
	AI       AIConfig       `yaml:"ai" json:"ai"`
}

type ServerConfig struct {
	// Bind address for the REST API. Default 127.0.0.1 (local only).
	// Set to 0.0.0.0 to allow other devices on your network to connect —
	// note the API has no authentication.
	Bind string `yaml:"bind" json:"bind"`
	Port int    `yaml:"port" json:"port"`
}

type CasambiConfig struct {
	// NetworkID is the Casambi cloud network ID, used to fetch credentials.
	NetworkID string `yaml:"network_id" json:"network_id"`
}

type HueConfig struct {
	BridgeIP  string `yaml:"bridge_ip" json:"bridge_ip"`
	Username  string `yaml:"username" json:"username"`
	ClientKey string `yaml:"clientkey" json:"clientkey"` // enables Entertainment (DTLS) streaming
	// EntertainmentArea is the entertainment configuration ID; required
	// together with ClientKey for streaming.
	EntertainmentArea     string `yaml:"entertainment_area" json:"entertainment_area"`
	EntertainmentChannels []int  `yaml:"entertainment_channels" json:"entertainment_channels"`
}

type SpotifyConfig struct {
	// NowPlayingURL is an endpoint returning the currently playing Spotify
	// track (see README for the expected JSON shape). Optional — enables
	// album-art color palettes and pause detection in reactive mode.
	NowPlayingURL string `yaml:"now_playing_url" json:"now_playing_url"`
}

type ReactiveConfig struct {
	// CasambiUnits and HueLights are the lights driven by reactive mode.
	CasambiUnits []uint16 `yaml:"casambi_units" json:"casambi_units"`
	HueLights    []string `yaml:"hue_lights" json:"hue_lights"`
}

type AIConfig struct {
	// AnthropicAPIKey enables AI track enrichment (genre, mood, lighting
	// direction) on top of the DSP song analyzer. Empty = disabled.
	AnthropicAPIKey string `yaml:"anthropic_api_key" json:"anthropic_api_key"`
	// Model overrides the default Claude model for enrichment calls.
	Model string `yaml:"model" json:"model"`
}

// Configured reports whether a Hue bridge is set up.
func (h HueConfig) Configured() bool {
	return h.BridgeIP != "" && h.Username != ""
}

// StreamingConfigured reports whether Hue Entertainment streaming is set up.
func (h HueConfig) StreamingConfigured() bool {
	return h.Configured() && h.ClientKey != "" && h.EntertainmentArea != ""
}

func Default() *Config {
	return &Config{
		Server: ServerConfig{Bind: "127.0.0.1", Port: 8080},
	}
}

// Dir returns the casambi-go config directory, honoring XDG_CONFIG_HOME.
func Dir() string {
	if base := os.Getenv("XDG_CONFIG_HOME"); base != "" {
		return filepath.Join(base, "casambi-go")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "."
	}
	return filepath.Join(home, ".config", "casambi-go")
}

func Path() string            { return filepath.Join(Dir(), "config.yaml") }
func CredentialsPath() string { return filepath.Join(Dir(), "credentials.json") }
func BPMCachePath() string    { return filepath.Join(Dir(), "bpm_cache.json") }

// ProfileStorePath is where analyzed track profiles (BPM, energy, mood) live.
func ProfileStorePath() string { return filepath.Join(Dir(), "track_profiles.json") }

// Load reads the config at path (or the default location when path is "").
// A missing file is not an error: it returns defaults and found=false.
func Load(path string) (cfg *Config, found bool, err error) {
	if path == "" {
		path = Path()
	}
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return Default(), false, nil
	}
	if err != nil {
		return nil, false, err
	}
	cfg = Default()
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, false, fmt.Errorf("parse %s: %w", path, err)
	}
	if cfg.Server.Bind == "" {
		cfg.Server.Bind = "127.0.0.1"
	}
	if cfg.Server.Port == 0 {
		cfg.Server.Port = 8080
	}
	return cfg, true, nil
}

const fileHeader = `# casambi-go configuration
# Generated by "casambi-go setup" — safe to edit by hand.
#
#   server.bind      127.0.0.1 = this machine only; 0.0.0.0 = whole LAN (no auth!)
#   casambi          network_id identifies your network in the Casambi cloud;
#                    credentials are cached in credentials.json in this directory
#   hue              leave bridge_ip/username empty if you have no Hue bridge;
#                    clientkey + entertainment_area enable 25 Hz streaming
#   spotify          optional now-playing endpoint for album-art colors
#   reactive         which lights music-reactive mode drives
#   ai               optional Anthropic API key for AI track enrichment
#                    (genre, mood, lighting direction per song)
`

// Save writes the config to path (or the default location when path is "").
func (c *Config) Save(path string) error {
	if path == "" {
		path = Path()
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	data, err := yaml.Marshal(c)
	if err != nil {
		return err
	}
	return os.WriteFile(path, append([]byte(fileHeader+"\n"), data...), 0600)
}

// ApplyEnvOverrides lets the pre-config-file environment variables win over
// the file, so existing setups keep working.
func (c *Config) ApplyEnvOverrides() {
	if v := os.Getenv("HUE_BRIDGE_IP"); v != "" {
		c.Hue.BridgeIP = v
	}
	if v := os.Getenv("HUE_USERNAME"); v != "" {
		c.Hue.Username = v
	}
	if v := os.Getenv("HUE_CLIENTKEY"); v != "" {
		c.Hue.ClientKey = v
	}
	if v := os.Getenv("HUE_ENTERTAINMENT_AREA"); v != "" {
		c.Hue.EntertainmentArea = v
	}
	if v := os.Getenv("SPOTIFY_NOW_PLAYING_URL"); v != "" {
		c.Spotify.NowPlayingURL = v
	}
	if v := os.Getenv("ANTHROPIC_API_KEY"); v != "" {
		c.AI.AnthropicAPIKey = v
	}
}
